CREATE DATABASE AeroOnTheFly;

USE AeroOnTheFly;

CREATE TABLE Passageiro(
	CPF VARCHAR(11) NOT NULL PRIMARY KEY,	
	Nome VARCHAR(50) NOT NULL,
	Nascimento DATE NOT NULL,
	Sexo VARCHAR(1),
	UltimaCompra DATE NOT NULL,
	Situacao VARCHAR(10)

);

CREATE TABLE CompanhiaAerea(
	CNPJ VARCHAR(14) CONSTRAINT PK_CompanhiaAerea PRIMARY KEY,
	RazaoSocial VARCHAR(50) NOT NULL,
	DataAbertura DATE NOT NULL,
	UltimoVoo DATE NOT NULL,
	DataCadastro DATE NOT NULL, 
	Situacao VARCHAR(10));

CREATE TABLE Aeronave(
	INSCRICAO VARCHAR(5) CONSTRAINT PK_Aeronave PRIMARY KEY,
	Capacidade INT NOT NULL,
	UltimaVenda DATE NOT NULL,
	DataCadastro DATE NOT NULL,
	Situacao VARCHAR(10));

CREATE TABLE CompanhiaPossueAeronave(
	CNPJ VARCHAR(14) CONSTRAINT FK_CompanhiaAerea FOREIGN KEY REFERENCES CompanhiaAerea(CNPJ),
	INSCRICAO VARCHAR(5) CONSTRAINT FK_Aeronave FOREIGN KEY REFERENCES Aeronave(INSCRICAO),
	CONSTRAINT PK_CompanhiaPossueAeronave PRIMARY KEY(CNPJ, INSCRICAO));

	CREATE TABLE Passagem(
	IDPASSAGEM CHAR(6) CONSTRAINT PK_Passagem PRIMARY KEY(IDPASSAGEM),
	Identificador INT IDENTITY,
	DataUltimaOperacao DATE NOT NULL,
	ValorPassagem DECIMAL(7,2) NOT NULL,
	Situacao VARCHAR(10),
	IDVOO CHAR(6) CONSTRAINT FK_PassagemVoo FOREIGN KEY REFERENCES Voo(IDVOO));

CREATE TABLE Voo(
	IDVOO CHAR(6) CONSTRAINT PK_Voo PRIMARY KEY,
	Identificador INT IDENTITY,
	Destino VARCHAR(3) NOT NULL,
	DataVoo DATE NOT NULL,
	HoraVoo TIME NOT NULL,
	DataCadastro DATE NOT NULL,
	Situacao VARCHAR(10));

CREATE TABLE AeronavePossueVoo(
	INSCRICAO VARCHAR(5) CONSTRAINT FK_AeronaveVoo FOREIGN KEY REFERENCES Aeronave(INSCRICAO),
	IDVOO CHAR(6) CONSTRAINT FK_Voo FOREIGN KEY REFERENCES Voo(IDVOO),
	Capacidade INT NOT NULL,
	AssentosOcupados INT,
	Passagem VARCHAR(10),
	CONSTRAINT PK_AeronavePossueVoo PRIMARY KEY(INSCRICAO, IDVOO));
	

	   	   
	


SELECT * FROM Passageiro
SELECT * FROM CompanhiaAerea
SELECT * FROM Aeronave
SELECT * FROM Passagem
SELECT * FROM Voo


CREATE TABLE RestritosCPF(	
	CPF VARCHAR(11) UNIQUE);

CREATE TABLE RestritosCNPJ(
	CNPJ VARCHAR(14) UNIQUE);